---
version: "2.1"
services:
  apprise-api:
    image: lscr.io/linuxserver/apprise-api
    container_name: apprise-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Athens
    volumes:
      - /portainer/Files/AppData/Config/apprise:/config
    ports:
      - 8006:8000  #changed from default 8000 
    restart: unless-stopped