version: "3"

services:
  app:
    image: wallabag/wallabag
    container_name: wallabag
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://127.0.0.1",
        ]
      interval: 1m
      timeout: 3s
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=http://127.0.0.1:8234
      - SYMFONY__ENV__SERVER_NAME="My Wallabag Instance"
    ports:
      - 127.0.0.1:8234:80
    volumes:
      - ./data:/var/www/wallabag/data
      - ./images:/var/www/wallabag/web/assets/images
